### ISSUE TITLE
App suggestion

### ISSUE THREAD

**Issue by comparesheriff** [LinuxCafeFederation/awesome-android#50]
### Name: 
Photok

### Short Description: 
Photok encrypts your photos on your device and keeps them safe from others.

### Source:
https://github.com/leonlatsch/Photok

### License:
Apache

### F-Droid: 
[https://f-droid.org/packages/dev.leonlatsch.photok/](https://f-droid.org/packages/dev.leonlatsch.photok/)

### Category:
Either Media or Privacy/Utils

**Comment by CipherOps** [comment]
Closed with #fba60c7
