### ISSUE TITLE
App request

### ISSUE THREAD

**Issue by Animyos** [LinuxCafeFederation/awesome-android#59]
Hello, I want to request the App "FairEmail". It's an awesome, secure E-Mail-App, and has its own website: [https://email.faircode.eu/](https://email.faircode.eu/) 
There is also a GitHub page:  [https://github.com/M66B/FairEmail/releases](https://github.com/M66B/FairEmail/releases)

Kind regards
Animyos Fox

**Comment by CipherOps** [comment]
I will get on this soon, thank you for the suggestion.
