### ISSUE TITLE
App Suggestion

### ISSUE THREAD

**Issue by MeFinity** [LinuxCafeFederation/awesome-android#66]
# Basic Tools
[Organic Maps](https://github.com/organicmaps/organicmaps)

[Material Flashlight](https://github.com/garmax1/material-flashlight)

# Misc
[Droid-ify](https://github.com/Iamlooker/Droid-ify)

[Vigilante](https://github.com/FunkyMuse/Vigilante)

# Fun
[Randomix](https://github.com/m-i-n-a-r/randomix)

[Antimine](https://github.com/lucasnlm/antimine-android)

**Comment by CipherOps** [comment]
Since the last update I've got a full-time job and life stuff so not as much time to devote to this anymore.

This is just a mirror, the project is maintained at https://gitlab.com/linuxcafefederation/awesome-android

You can submit a PR there and I'll accept it.
