### ISSUE TITLE
[Suggestion] Disroot app

### ISSUE THREAD

**Issue by Animyos** [LinuxCafeFederation/awesome-android#68]
I would like to suggest the Disroot App.
Disroot is a toolbox of different free and privacy friendly tools, such as a file uploader (like WeTransfer) or a hosted Jitsi Meet system.

The toolbox can be used online, see [https://disroot.org](https://disroot.org), but there is also an Android application, available on F-Droid ([https://f-droid.org/packages/org.disroot.disrootapp](https://f-droid.org/packages/org.disroot.disrootapp)) and on his own git repository ([https://git.disroot.org/Disroot/disapp](https://git.disroot.org/Disroot/disapp)).

**Comment by CipherOps** [comment]
App link is now a 500.
