### ISSUE TITLE
App suggestion

### ISSUE THREAD

**Issue by HoriKyoukosimp** [LinuxCafeFederation/awesome-android#72]
Frosty https://github.com/tommyxchow/frosty
Alternative Twitch client with alot of customizable feature and support 3rd party emote (BTTV, FFZ, 7TV)

**Comment by CipherOps** [comment]
Since the last update I've got a full-time job and life stuff so not as much time to devote to this anymore.

This is just a mirror, the project is maintained at https://gitlab.com/linuxcafefederation/awesome-android

You can submit a PR there and I'll accept it.
