### ISSUE TITLE
pending PR

### ISSUE THREAD

**Issue by imxade** [LinuxCafeFederation/awesome-android#73]
https://codeberg.org/LinuxCafeFederation/awesome-android/pulls/3

I think, It has not been seen yet.

**Comment by CipherOps** [comment]
Since the last update I've got a full-time job and life stuff so not as much time to devote to this anymore.

This is just a mirror, the project is maintained at https://gitlab.com/linuxcafefederation/awesome-android

You can submit a PR there and I'll accept it.
